"""
Django settings for sistema_reservas project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _cargar_entorno_local():
    """Carga .env solo para desarrollo, sin reemplazar variables del servidor."""
    ruta = BASE_DIR / '.env'
    if not ruta.exists():
        return
    for linea in ruta.read_text(encoding='utf-8').splitlines():
        linea = linea.strip()
        if not linea or linea.startswith('#') or '=' not in linea:
            continue
        nombre, valor = linea.split('=', 1)
        nombre = nombre.strip()
        valor = valor.strip().strip('"').strip("'")
        # Algunos lanzadores locales crean las variables con valor vacío.
        # En ese caso sí debe utilizarse el valor privado de .env. Una
        # variable real de Render nunca se reemplaza.
        if nombre and not os.environ.get(nombre):
            os.environ[nombre] = valor


_cargar_entorno_local()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En producción se lee desde variable de entorno SECRET_KEY
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-clave-solo-para-desarrollo-local'
)

# DEBUG = False en producción (Render setea la variable DJANGO_DEBUG=False)
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Render agrega automáticamente el dominio; también permite hosts locales
ALLOWED_HOSTS = os.environ.get(
    'ALLOWED_HOSTS',
    '127.0.0.1,localhost'
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Archivos estáticos en producción
    'whitenoise.runserver_nostatic',
    # Apps del proyecto
    'sistema',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise debe ir justo después de SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_reservas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'sistema' / 'templades',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Hace disponible `rol` en todas las plantillas. Así el
                # administrador conserva todos los controles aunque una vista
                # no envíe el rol manualmente en su contexto.
                'sistema.context_processors.rol_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_reservas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Prioridad de configuración:
#   1. DATABASE_URL  → Render la inyecta automáticamente al conectar PostgreSQL
#   2. Variables individuales POSTGRES_* → útil para entornos propios
#   3. SQLite local  → desarrollo sin configuración extra

DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            # Los proxies PostgreSQL de servicios administrados pueden cerrar
            # conexiones inactivas entre dos peticiones. No conservarlas evita
            # que el POST de login deje al dashboard una conexión obsoleta.
            conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '0')),
            conn_health_checks=True,
        )
    }
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].setdefault('connect_timeout', 10)
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'Inmobiliaria'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
            'PORT': int(os.environ.get('POSTGRES_PORT', 5432) or 5432),
            'OPTIONS': {'sslmode': 'require'},
        }
    }
else:
    if not DEBUG:
        raise ImproperlyConfigured(
            'DATABASE_URL (o las variables POSTGRES_*) es obligatoria en producción. '
            'SQLite no es persistente en servicios como Render.'
        )
    # Desarrollo local con SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'Inmobiliaria.db'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'sistema_reservas' / 'static',
]

# Carpeta donde collectstatic reúne todos los archivos estáticos (producción)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: compresión y caché de archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ─────────────────────────────────────────────
# Configuración de autenticación Django Auth
# ─────────────────────────────────────────────
LOGIN_URL          = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Grupos de roles del sistema
# - Administrador: acceso total
# - Agente: gestiona propiedades, visitas y contratos
# - Comprador: agenda visitas y ve sus propiedades

# Subir archivos de media (fotos, contratos)
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ------------------------------------------------------------------
# Email (SMTP) - usado para enviar contratos y notificaciones
# Se pueden sobrescribir mediante variables de entorno en producción
# ------------------------------------------------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# Google muestra las contraseñas de aplicación separadas en bloques. Render
# puede conservar espacios normales o no separables al pegarlas; SMTP necesita
# recibir los 16 caracteres continuos.
EMAIL_HOST_PASSWORD = ''.join(os.environ.get('EMAIL_HOST_PASSWORD', '').split())
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Evita que una falla de red/SMTP deje colgada una petición web.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 8))

# En Render Free los puertos SMTP están bloqueados. Si BREVO_API_KEY está
# configurada, las facturas se envían mediante la API HTTPS de Brevo.
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '').strip()
BREVO_API_URL = os.environ.get('BREVO_API_URL', 'https://api.brevo.com/v3/smtp/email')
BREVO_SENDER_EMAIL = os.environ.get('BREVO_SENDER_EMAIL', EMAIL_HOST_USER).strip()
BREVO_SENDER_NAME = os.environ.get('BREVO_SENDER_NAME', 'Conexión Inmobiliaria').strip()
BREVO_TIMEOUT = int(os.environ.get('BREVO_TIMEOUT', 20))
