# Generated by Django 5.2.15 on 2026-07-29 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteInmobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=13, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='agentes/')),
                ('comision_pct', models.DecimalField(decimal_places=2, default=3.0, help_text='Porcentaje de comisión sobre la venta', max_digits=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agente Inmobiliario',
                'verbose_name_plural': 'Agentes Inmobiliarios',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=13, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('presupuesto_max', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto máximo en USD', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('prospecto', 'Prospecto'), ('activo', 'Activo'), ('cerrado', 'Cerrado'), ('inactivo', 'Inactivo')], default='prospecto', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, help_text='Agente asignado a este comprador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compradores', to='sistema.agenteinmobiliario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('terreno', 'Terreno'), ('local_comercial', 'Local Comercial'), ('oficina', 'Oficina')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area_m2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dormitorios', models.PositiveSmallIntegerField(default=0)),
                ('banos', models.PositiveSmallIntegerField(default=0)),
                ('parqueaderos', models.PositiveSmallIntegerField(default=0)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('vendida', 'Vendida'), ('no_disponible', 'No Disponible')], default='disponible', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, help_text='Agente captador de la propiedad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propiedades', to='sistema.agenteinmobiliario')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ContratoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('comision_calculada', models.DecimalField(decimal_places=2, default=0, help_text='Comisión en USD calculada al firmar', max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('firmado', 'Firmado'), ('anulado', 'Anulado')], default='borrador', max_length=15)),
                ('documento', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='sistema.agenteinmobiliario')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='sistema.comprador')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='sistema.propiedad')),
            ],
            options={
                'verbose_name': 'Contrato de Venta',
                'verbose_name_plural': 'Contratos de Venta',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_min', models.PositiveSmallIntegerField(default=30, help_text='Duración estimada en minutos')),
                ('orden_ruta', models.PositiveSmallIntegerField(default=1, help_text='Posición en la ruta del día')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('confirmado_por_cliente', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='sistema.agenteinmobiliario')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='sistema.comprador')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='sistema.propiedad')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['fecha_hora', 'orden_ruta'],
            },
        ),
    ]
