# Generated by Django 5.2.15 on 2026-08-06 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def crear_facturas_contratos_firmados(apps, schema_editor):
    ContratoVenta = apps.get_model('sistema', 'ContratoVenta')
    Factura = apps.get_model('sistema', 'Factura')
    secuencias = {}
    for contrato in ContratoVenta.objects.filter(estado='firmado').order_by('fecha_firma', 'pk'):
        fecha = contrato.fecha_firma or django.utils.timezone.localdate()
        year = fecha.year
        secuencias[year] = secuencias.get(year, 0) + 1
        Factura.objects.get_or_create(
            contrato=contrato,
            defaults={
                'numero_factura': f'FAC-{year}-{secuencias[year]:06d}',
                'fecha_emision': fecha,
                'valor_venta': contrato.precio_acordado,
                'total': contrato.precio_acordado,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_imagefield_to_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=30, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('correo_enviado', models.BooleanField(default=False)),
                ('fecha_envio_correo', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='sistema.contratoventa')),
            ],
            options={
                'verbose_name': 'Factura / Comprobante',
                'verbose_name_plural': 'Facturas / Comprobantes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.RunPython(crear_facturas_contratos_firmados, migrations.RunPython.noop),
    ]
