# Generated by Django 5.2.15 on 2026-08-06 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_factura_comprobante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=500)),
                ('estado_http', models.PositiveSmallIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=500)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('cuerpo_respuesta', models.BinaryField(blank=True, default=bytes)),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operación offline sincronizada',
                'verbose_name_plural': 'Operaciones offline sincronizadas',
                'ordering': ['-procesado_en'],
            },
        ),
    ]
